name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "25 23 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: leokang28/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: 8f1704f078091ed35cc87fc755521197
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
# commit

